### ISSUE TITLE
Login does not work when using Amazon login for eero, is there a way around this?

### ISSUE THREAD

**Issue by krishnadasmallya** [343max/eero-client#18]
Login does not work when using Amazon login for eero, is there a way around this?

**Comment by piotrekjeremicz** [comment]
I would like to find the answer too. The problem is when you are using Eero routers in other country that Amazon officially supports. In that case amazon account is only one method to log in.

**Comment by krishnadasmallya** [comment]
Felt like there is too much work involved to make the Amazon integration work, so I logged out from the app and started registration using email/phone then linked amazon account. So the primary login stays as email & phone and that did the trick for me.
