### ISSUE TITLE
Add to PyPI for easier installing

### ISSUE THREAD

**Issue by yanokwa** [343max/eero-client#7]
I'd love to be able to run `pip install eero-client` and have an easy install and easy updates to eero-client. 

https://packaging.python.org/tutorials/packaging-projects has instructions on how to do it. I think much of it is done, but the project needs to be uploaded.

**Comment by 16BitS3G4l** [comment]
Hey @yanokwa I'm not sure if this is still much of a problem for you, but I've taken the time to publish this project to PyPI. You can find it here: https://pypi.org/project/eero/

Hope it helps out 👍

**Comment by yanokwa** [comment]
It does help! Thanks for taking the initiative, @dev-segal.

I would feel better if it linked to this repo though. Or if @343max was a maintainer on the pypi account.

**Comment by 16BitS3G4l** [comment]
@yanokwa I'm still waiting for @343max to provide a PyPI username so I can transfer ownership of the project, but hopefully pull request #10 puts your mind at ease :+1:

**Comment by 343max** [comment]
Hey! Sorry, didn't get the memo. My username over there is 343max, same as here.

**Comment by 16BitS3G4l** [comment]
No problemo

**Comment by yanokwa** [comment]
Closed by #10
